### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by aromagnoli** [NoobBlocker-dev/NoobBlocker#1]
So... after a long while I decided to use your addon again, but I was broken. I had an early version of it and a friend of mine found your repository. I downloaded and went through the code. Fixed it, but my knowledge on LUA and your addon doesn't go far. There is a way for automatic decline? I mean, if Im blocking the realm or player I don't want to click on decline once again. I want to auto decline them, just like the in game behavior when you apply to a group who have a threshold ilvl and you get instant decline. Is it possible?

**Comment by NoobBlocker-dev** [comment]
could you submit your fix as a pull request, or detail what you fixed so I can fix it? I'm no longer subbed.

As far as auto declining, due to how world quest group finders were broken auto accepting / declining is a blocked api call by blizzard.
